title: like-a-robot's Homepage
page-top-title: 跟机器人一样
top-section-bg-text: Artificial intelligence (AI)
home-subtitle: like-a-robot &ensp;|&ensp;跟机器人一样
copyright-text: '&copy; like-a-robot 2024-2025. All Rights Reserved.'
